# Generated by Django 5.0.14 on 2025-09-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
