# Generated by Django 5.0.14 on 2025-09-23 12:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requestlog_ip_address_requestlog_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV文件'), ('txt', '文本文件'), ('xlsx', 'Excel文件'), ('r', 'R脚本'), ('rmd', 'R Markdown'), ('json', 'JSON文件'), ('xml', 'XML文件'), ('other', '其他')], max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('file_content', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('encoding', models.CharField(default='utf-8', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='core.requestlog')),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
